# Note: Remember to update the account baseline SCP when making changes here
Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Admin
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "092251750008" # ortizaggies-org
            Action: ["sts:AssumeRole"]
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: "true"
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/AdministratorAccess"]
