# Note: Remember to update the account baseline SCP when making changes here
AWSTemplateFormatVersion: "2010-09-09"
Description: Account Baseline StackSet is applied accross all accounts
Parameters:
  CloudTrailBucket:
    Type: String
    Description: Name of the bucket used by the organization CloudTrail
    Default: ortizaggies-org-cloudtrail
  OrgID:
    Description: Organization ID
    Type: String
    Default: o-jubqj38nma
Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Admin
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "092251750008" # ortizaggies-org
            Action: ["sts:AssumeRole"]
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: "true"
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/AdministratorAccess"]
  AccessAnalyzerMonitorServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AccessAnalyzerMonitorServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: access-analyzer.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref AccessAnalyzerMonitorServicePolicy
  AccessAnalyzerMonitorServicePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows access to the Organization CloudTrail
      ManagedPolicyName: AccessAnalyzerMonitorServicePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "cloudtrail:GetTrail"
            Resource: "*"
          - Effect: Allow
            Action:
              - "iam:GenerateServiceLastAccessedDetails"
              - "iam:GetServiceLastAccessedDetails"
            Resource: "*"
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${CloudTrailBucket}"
              - !Sub "arn:aws:s3:::${CloudTrailBucket}/*"
  UtilityBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub "utility-bucket-${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter7Days
            Status: Enabled
            ExpirationInDays: 7

  AccountAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    DependsOn: UtilityBucket
    Properties:
      Name: account
      Description: Account queries, with results in the utility bucket
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        ResultConfiguration:
          OutputLocation: !Sub "s3://utility-bucket-${AWS::Region}-${AWS::AccountId}/"
          EncryptionConfiguration:
            EncryptionOption: SSE_S3

  AccountBaselineGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: account
        Description: Database to hold tables for every account

  CloudTrailAthenaTable:
    Type: AWS::Glue::Table
    DependsOn: AccountBaselineGlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AccountBaselineGlueDatabase
      TableInput:
        Name: cloudtrail
        Description: Searches the Organization CloudTrail
        TableType: EXTERNAL_TABLE
        PartitionKeys:
          - Name: region
            Type: string
          - Name: date_partition
            Type: string
        Parameters:
          "projection.enabled": "true"
          "projection.date_partition.type": date
          "projection.date_partition.format": yyyy/MM/dd
          "projection.date_partition.range": NOW-31DAYS,NOW
          "projection.date_partition.interval": "1"
          "projection.date_partition.interval.unit": DAYS
          "projection.region.type": enum
          "projection.region.values": af-south-1,ap-east-1,ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,cn-north-1,cn-northwest-1,eu-central-1,eu-north-1,eu-south-1,eu-west-1,eu-west-2,eu-west-3,me-south-1,sa-east-1,us-east-1,us-east-2,us-gov-east-1,us-gov-west-1,us-west-1,us-west-2
          "storage.location.template": !Sub "s3://${CloudTrailBucket}/AWSLogs/${OrgID}/${AWS::AccountId}/CloudTrail/${!region}/${!date_partition}/"
        Retention: 0
        StorageDescriptor:
          Location: !Sub "s3://${CloudTrailBucket}/AWSLogs/${OrgID}/${AWS::AccountId}/"
          InputFormat: com.amazon.emr.cloudtrail.CloudTrailInputFormat
          SerdeInfo:
            SerializationLibrary: com.amazon.emr.hive.serde.CloudTrailSerde
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
            - Name: eventversion
              Type: string
            - Name: useridentity
              Type: struct<type:string,principalid:string,arn:string,accountid:string,invokedby:string,accesskeyid:string,userName:string,sessioncontext:struct<attributes:struct<mfaauthenticated:string,creationdate:string>,sessionissuer:struct<type:string,principalId:string,arn:string,accountId:string,userName:string>>>
            - Name: eventtime
              Type: string
            - Name: eventsource
              Type: string
            - Name: eventname
              Type: string
            - Name: awsregion
              Type: string
            - Name: sourceipaddress
              Type: string
            - Name: useragent
              Type: string
            - Name: errorcode
              Type: string
            - Name: errormessage
              Type: string
            - Name: requestparameters
              Type: string
            - Name: responseelements
              Type: string
            - Name: additionaleventdata
              Type: string
            - Name: requestid
              Type: string
            - Name: eventid
              Type: string
            - Name: resources
              Type: array<struct<ARN:string,accountId:string,type:string>>
            - Name: eventtype
              Type: string
            - Name: apiversion
              Type: string
            - Name: readonly
              Type: string
            - Name: recipientaccountid
              Type: string
            - Name: serviceeventdetails
              Type: string
            - Name: sharedeventid
              Type: string
            - Name: vpcendpointid
              Type: string
