AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket to store organization CloudTrail
Parameters:
  BucketName:
    Description: The name of the bucket to store CloudTrail
    Type: String
    Default: ortizaggies-org-cloudtrail
  OrgID:
    Description: Organization ID
    Type: String
    Default: o-jubqj38nma
Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter30Days
            Status: Enabled
            ExpirationInDays: 30
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${BucketName}"
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/AWSLogs/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AdminRead
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/Admin"
            Action:
              - s3:Get*
              - s3:List*
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
          - Sid: CrossAccountListBucket
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}"
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - !Ref OrgID
              StringLikeIfExists:
                "s3:prefix": !Sub "AWSLogs/${OrgID}/${!aws:PrincipalAccount}/*"
              ArnLike:
                "aws:PrincipalArn":
                  - arn:aws:iam::*:role/Admin
                  - arn:aws:iam::*:role/AccessAnalyzerMonitorServiceRole
          - Sid: CrossAccountGetObject
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/AWSLogs/${OrgID}/${!aws:PrincipalAccount}/*"
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - !Ref OrgID
              ArnLike:
                "aws:PrincipalArn":
                  - arn:aws:iam::*:role/Admin
                  - arn:aws:iam::*:role/AccessAnalyzerMonitorServiceRole
  OrganizationGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: organization
        Description: Database to hold tables for the organization
  CloudTrailAthenaTable:
    Type: AWS::Glue::Table
    DependsOn: OrganizationGlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref OrganizationGlueDatabase
      TableInput:
        Name: cloudtrail
        Description: Searches the Organization CloudTrail
        TableType: EXTERNAL_TABLE
        PartitionKeys:
          - Name: account
            Type: string
          - Name: region
            Type: string
          - Name: date_partition
            Type: string
        Parameters:
          "projection.enabled": "true"
          "projection.date_partition.type": date
          "projection.date_partition.format": yyyy/MM/dd
          "projection.date_partition.range": NOW-31DAYS,NOW
          "projection.date_partition.interval": "1"
          "projection.date_partition.interval.unit": DAYS
          "projection.region.type": enum
          "projection.region.values": af-south-1,ap-east-1,ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,cn-north-1,cn-northwest-1,eu-central-1,eu-north-1,eu-south-1,eu-west-1,eu-west-2,eu-west-3,me-south-1,sa-east-1,us-east-1,us-east-2,us-gov-east-1,us-gov-west-1,us-west-1,us-west-2
          "projection.account.type": injected
          "storage.location.template": !Sub "s3://${BucketName}/AWSLogs/${OrgID}/${!account}/CloudTrail/${!region}/${!date_partition}/"
        Retention: 0
        StorageDescriptor:
          Location: !Sub "s3://${BucketName}/AWSLogs/${OrgID}/"
          InputFormat: com.amazon.emr.cloudtrail.CloudTrailInputFormat
          SerdeInfo:
            SerializationLibrary: com.amazon.emr.hive.serde.CloudTrailSerde
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          # Note, there are some fields that are not yet supported by CloudTrailSerde:
          # useridentity.sessionContext.webIdFederationData (string)
          # managementevent (boolean)
          # eventcategory (string)
          # addendum (string)
          # sessioncredentialfromconsole (string)
          # edgedevicedetails (string)
          # tlsdetails (string)
          Columns:
            - Name: eventversion
              Type: string
            - Name: useridentity
              Type: struct<type:string,principalid:string,arn:string,accountid:string,invokedby:string,accesskeyid:string,userName:string,sessioncontext:struct<attributes:struct<mfaauthenticated:string,creationdate:string>,sessionissuer:struct<type:string,principalId:string,arn:string,accountId:string,userName:string>>>
            - Name: eventtime
              Type: string
            - Name: eventsource
              Type: string
            - Name: eventname
              Type: string
            - Name: awsregion
              Type: string
            - Name: sourceipaddress
              Type: string
            - Name: useragent
              Type: string
            - Name: errorcode
              Type: string
            - Name: errormessage
              Type: string
            - Name: requestparameters
              Type: string
            - Name: responseelements
              Type: string
            - Name: additionaleventdata
              Type: string
            - Name: requestid
              Type: string
            - Name: eventid
              Type: string
            - Name: resources
              Type: array<struct<ARN:string,accountId:string,type:string>>
            - Name: eventtype
              Type: string
            - Name: apiversion
              Type: string
            - Name: readonly
              Type: string
            - Name: recipientaccountid
              Type: string
            - Name: serviceeventdetails
              Type: string
            - Name: sharedeventid
              Type: string
            - Name: vpcendpointid
              Type: string
